name: Publish to Play store

on:
  push:
    # Branch only during testing
    #branches:
    #  - master
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: perform the validation
      uses: gradle/actions/wrapper-validation@v3

    - name: perform the JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: perform Gradle caching
      uses: gradle/actions/setup-gradle@v3

    - name: run custom tasks to ensure app can be published on play store
      run: ./gradlew checkLanguages checkFastlane

    - name: build and deploy
      run: ./deploy_playstore.sh
      env:
        SERVICEACCOUNTJSON: ${{ secrets.SERVICEACCOUNTJSON }}
        KEYSTOREPASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
        KEYALIAS: ${{ secrets.KEYALIAS }}
